sudo: required
services:
  - docker

before_install:
  - docker build -t elcinico/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run  -e CI=true elcinico/react-test npm test -- --coverage

after_success:
  - docker build -t elcinico/multi-client ./client
  - docker build -t elcinico/multi-nginx ./nginx
  - docker build -t elcinico/multi-server ./server
  - docker build -t elcinico/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push elcinico/multi-client
  - docker push elcinico/multi-nginx
  - docker push elcinico/multi-server
  - docker push elcinico/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-860457455961"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
